name: simpler
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
style: italic
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  font_awesome_flutter: 9.2.0
  intl: 0.17.0
  blur: 3.0.0
  auto_size_text: 3.0.0
  get_storage: 2.0.3
  sqflite: 2.0.2
  flutter_native_splash: 1.3.3
  animated_splash_screen: 1.1.0
  page_transition: 2.0.1-nullsafety.0
  fullscreen: 1.0.3
  lottie: 1.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: 0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#F8F6FD"
  image: assets/icons/brand.png
  android_gravity: center
  fullscreen: true
  android: true
  ios: true
  web: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/brand.png"
  adaptive_icon_background: "#F8F6FD"

flutter:
  assets:
    - assets/
    - assets/lottie/
    - assets/icons/
    - assets/icons/project/
    - assets/users/male/
    - assets/users/female/
  uses-material-design: true

fonts:
  - family: Source Sans Pro
    fonts:
      - asset: assets/fonts/SourceSansPro-Regular.ttf
      - asset: assets/fonts/SourceSansPro-Black.ttf
      - asset: assets/fonts/SourceSansPro-Bold.ttf
      - asset: assets/fonts/SourceSansPro-SemiBold.ttf
      - asset: assets/fonts/SourceSansPro-Italic.ttf
