name: simpler
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
style: italic
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  font_awesome_flutter: 9.2.0
  intl: 0.17.0
  blur: 3.0.0
  auto_size_text: 3.0.0
  get_storage: 2.0.3
  sqflite: 2.0.2
  liquid_progress_indicator: 0.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/icons/project/
    - assets/users/male/
    - assets/users/female/
  uses-material-design: true

fonts:
  - family: Source Sans Pro
    fonts:
      - asset: assets/fonts/SourceSansPro-Regular.ttf
      - asset: assets/fonts/SourceSansPro-Black.ttf
      - asset: assets/fonts/SourceSansPro-Bold.ttf
      - asset: assets/fonts/SourceSansPro-SemiBold.ttf
      - asset: assets/fonts/SourceSansPro-Italic.ttf
